spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study  ?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: 18897793826@163.com
    password: BSX8mPRLBC3RZ6vs
    properties:
      from: 18897793826@163.com
  data:
    redis:
      database: 0
      port: 6379
      host: localhost
      password: ""